post http://localhost:3003/api/users 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IktyaXN0amFuIFJhamFuaWVtaSIsImlkIjoiNjFhMzg2MGRkMmI3MjgyM2U2M2E1NGI3IiwiaWF0IjoxNjM4MTE3NzgxfQ.fGuvcQcXUXvqkbUZ3iJwXW-zilWUpoiZVTvjHwG2Kc0


{
"username": "user1234", "name": "user1234", "password": "password", "blogs": ["Jormo", "jorma"]
}